# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.9
  - 3.8
  - 3.7

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -U tox-travis
    - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then pip install twine; pip install importlib-metadata>=1; fi

# importlib-metadata is temporary
# See https://travis-ci.community/t/cant-deploy-to-pypi-anymore-pkg-resources-contextualversionconflict-importlib-metadata-0-18/10494

# Command to run tests, e.g. python setup.py test
script: tox


